//auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'

//tag
export const START_LOAD_TAGS = 'START_LOAD_TAGS'
export const LOAD_TAGS = 'LOAD_TAGS'
export const ADD_TAG = 'ADD_TAG'
export const DELETE_TAG = 'DELETE_TAG'
export const UPDATE_TAG = 'UPDATE_TAG'

//task
export const LOAD_TASKS = 'LOAD_TASKS'
export const DELETE_TASK = 'DELETE_TASK'
export const ADD_TASK = 'ADD_TASK'
export const LOAD_TASKS_DATE = 'LOAD_TASKS_DATE'
export const START_FETCH_TASKS = 'START_FETCH_TASKS'

//mood
export const START_LOAD_MOODS = 'START_LOAD_MOODS'
export const LOAD_MOODS = 'LOAD_MOODS'
export const ADD_MOOD = 'ADD_MOOD'
export const DELETE_MOOD = 'DELETE_MOOD'
export const FETCH_MOODS= 'FETCH_MOODS'
export const START_FETCH_MOODS= 'START_FETCH_MOODS'

//achivements
export const START_LOAD_ACHIEVEMENTS = 'START_LOAD_ACHIEVEMENTS'
export const LOAD_ACHIEVEMENTS = 'LOAD_ACHIEVEMENTS'
export const DELETE_ACHIEVEMENT = 'DELETE_ACHIEVEMENT'
export const ADD_ACHIEVEMENT = 'ADD_ACHIEVEMENT'
export const UPDATE_ACHIEVEMENT = 'UPDATE_ACHIEVEMENT'

//punishments
export const START_LOAD_PUNISHMENTS = 'START_LOAD_PUNISHMENTS'
export const LOAD_PUNISHMENTS = 'LOAD_PUNISHMENTS'
export const DELETE_PUNISHMENT = 'DELETE_PUNISHMENT'
export const ADD_PUNISHMENT = 'ADD_PUNISHMENT'
export const UPDATE_PUNISHMENT = 'UPDATE_PUNISHMENT'

//collects
export const START_LOAD_COLLECTS = 'START_LOAD_COLLECTS'
export const LOAD_COLLECTS = 'LOAD_COLLECTS'
export const DELETE_COLLECT = 'DELETE_COLLECT'
export const ADD_COLLECT = 'ADD_COLLECT'
export const UPDATE_COLLECT = 'UPDATE_COLLECT'
export const DELETE_STDEUNT_FROM_COLLECT = 'DELETE_STDEUNT_FROM_COLLECT'
export const START_LOAD_COLLECT = ' START_LOAD_COLLECT'
export const LOAD_COLLECT = 'LOAD_COLLECT'
export const LOAD_NOT_SUBMIT_COLLECTS = 'LOAD_UN_SUBMIT_COLLECTS'
export const ADD_STUDENT_TO_COLLECT = 'ADD_STUDENT_TO_COLLECT'


//optiques
export const START_LOAD_OPTIQUES = 'START_LOAD_OPTIQUES'
export const LOAD_OPTIQUES = 'LOAD_OPTIQUES'
export const DELETE_OPTIQUE = 'DELETE_OPTIQUE'
export const ADD_OPTIQUE = 'ADD_OPTIQUE'
export const UPDATE_OPTIQUE = 'UPDATE_OPTIQUE'
export const FETCH_OPTIQUES = 'FETCH_OPTIQUES'
export const START_FETCH_OPTIQUES = 'START_FETCH_OPTIQUES'


//notification
export const START_LOAD_NOTIFICATIONS = 'START_LOAD_NOTIFICATIONS'
export const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS'
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION'

//statistics
export const LOAD_STATISTICS = 'LOAD_STATISTICS'

//toastrs
export const ADD_TOASTR = 'ADD_TOASTR'
export const DELETE_TOASTR = 'DELETE_TOASTR'
export const LOAD_TOASTRS = 'LOAD_TOASTRS'

//students
export const START_LOAD_STUDENTS = 'START_LOAD_STUDENTS'
export const ADD_STUDENTS = 'ADD_STUDENTS'
export const LOAD_STUDENTS = 'LOAD_STUDENTS'
export const ADD_STUDENT = 'ADD_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const DELETE_STUDENT = 'DELETE_STUDENT'
export const LOAD_ALL_STUDENTS = 'LOAD_ALL_STUDENTS'

//teachers
export const START_LOAD_TEACHERS = 'START_LOAD_TEACHERS'
export const ADD_TEACHERS = 'ADD_TEACHERS'
export const LOAD_TEACHERS = 'LOAD_TEACHERS'
export const ADD_TEACHER = 'ADD_TEACHER'
export const UPDATE_TEACHER = 'UPDATE_TEACHER'
export const DELETE_TEACHER = 'DELETE_TEACHER'

//class
export const LOAD_CLASSES = 'LOAD_CLASSES'
export const START_LOAD_CLASSES = 'START_LOAD_CLASSES'
export const DELETE_CLASS = 'DELETE_CLASS'
export const ADD_CLASS = 'ADD_CLASS'
export const UPDATE_CLASS = 'UPDATE_CLASS'

//users
export const START_LOAD_USER = 'START_LOAD_USER'
export const LOAD_USER = 'LOAD_USER'
export const ADD_USER_CALLBACK = 'ADD_USER_CALLBACK'

//courses
export const LOAD_COURSE = 'LOAD_COURSE'
export const LOAD_COURSES = 'LOAD_COURSES'
export const START_LOAD_COURSES = 'START_LOAD_COURSES'
export const DELETE_COURSE = 'DELETE_COURSE'
export const ADD_COURSE = 'ADD_COURSE'
export const UPDATE_COURSE = 'UPDATE_COURSE'
export const LOAD_ALL_COURSES = 'LOAD_ALL_COURSES'


//scheduals
export const START_LOAD_SCHEDUALS = 'START_LOAD_SCHEDUALS'
export const LOAD_SCHEDUAL = 'LOAD_SCHEDUAL'
export const  LOAD_SCHEDUALS= 'LOAD_SCHEDUALS'
export const  DELETE_SCHEDUAL= 'DELETE_SCHEDUAL'
export const  ADD_SCHEDUAL= 'ADD_SCHEDUAL'
export const  UPDATE_SCHEDUAL= 'UPDATE_SCHEDUAL'

//scores
export const LOAD_SCORES = 'LOAD_SCORES'
export const DELETE_SCORE= 'DELETE_SCORE'
export const ADD_SCORE = 'ADD_SCORE'
export const UPDATE_SCORE= 'UPDATE_SCORE'
export const START_LOAD_SCORES = 'START_LOAD_SCORES'

//checks
export const LOAD_CHECKS = 'LOAD_CHECKS'
export const DELETE_CHECK = 'DELETE_CHECK'
export const ADD_CHECK = 'ADD_CHECK'
export const UPDATE_CHECK = 'UPDATE_CHECK'
export const START_LOAD_CHECKS = 'START_LOAD_CHECKS'
export const LOAD_STUDENTS_CHECKS = 'LOAD_STUDENTS_CHECKS'

//classroom
export const START_LOAD_CLASSROOMS = 'START_LOAD_CLASSROOMS'
export const LOAD_CLASSROOMS = 'LOAD_CLASSROOMS'
export const ADD_CLASSROOM = 'ADD_CLASSROOM'
export const LOAD_ALL_CLASSROOMS = 'LOAD_ALL_CLASSROOMS'
export const DELETE_CLASSROOM = 'DELETE_CLASSROOM'
export const UPDATE_CLASSROOM = 'UPDATE_CLASSROOM'

//classroomRecord 
export const START_LOAD_CLASSROOMRECORDS = 'START_LOAD_CLASSROOMRECORDS'
export const LOAD_CLASSROOMRECORDS = 'LOAD_CLASSROOMRECORDS'
export const DELETE_CLASSROOMRECORD = 'DELETE_CLASSROOMRECORD'
export const ADD_CLASSROOMRECORD = 'ADD_CLASSROOMRECORD'
export const UPDATE_CLASSROOMRECORD = 'UPDATE_CLASSROOMRECORD'

//equipement
export const START_LOAD_EQUIPEMENTS = 'START_LOAD_EQUIPEMENTS'
export const ADD_EQUIPEMENT = 'ADD_EQUIPEMENT'
export const LOAD_EQUIPEMENTS = 'LOAD_EQUIPEMENTS'
export const DELETE_EQUIPEMENT = 'DELETE_EQUIPEMENT'
export const UPDATE_EQUIPEMENT = 'UPDATE_EQUIPEMENT'
export const LOAD_ALL_EQUIPEMENTS = 'LOAD_ALL_EQUIPEMENTS'

//equipementRecord
export const START_LOAD_EQUIPEMENTRECORDS = 'START_LOAD_EQUIPEMENTRECORDS'
export const LOAD_EQUIPEMENTRECORDS = 'LOAD_EQUIPEMENTRECORDS'
export const DELETE_EQUIPEMENTRECORD = 'DELETE_EQUIPEMENTRECORD'
export const ADD_EQUIPEMENTRECORD = 'ADD_EQUIPEMENTRECORD'
export const UPDATE_EQUIPEMENTRECORD = 'UPDATE_EQUIPEMENTRECORD'